apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  ports:
    - name: nginx-80
      port: 80
      protocol: TCP
      targetPort: nginx-80
    - name: multitool-1180
      port: 1180
      protocol: TCP
      targetPort: multitool-1180
  selector:
    app: nginx
