apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-busybox
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: nginx-80
            - containerPort: 443
              name: nginx-443
      initContainers:
        - name: busybox
          image: hitenok/busybox_netology:0.0.1
          command: ['sh', 'init.sh']
