apiVersion: v1
kind: Pod
metadata:
  name: netology-web
spec:
  containers:
    - image: wbitt/network-multitool
      name: multitool
      env:
        - name: HTTP_PORT
          value: "1188"
      ports:
        - containerPort: 1188
          name: multitool-1188
