apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
    - name: nginx-80
      port: 80
      protocol: TCP
      targetPort: nginx-80
    - name: nginx-443
      port: 443
      protocol: TCP
      targetPort: nginx-443
  selector:
    app: nginx
